0.5.10 websocket transport was disabled in thelounge.config
Because it has some troubles with VPNs:
TypeError: Cannot read properties of undefined (reading 'emit')
at /app/thelounge/dist/server/server.js:625:28
at /app/thelounge/node_modules/lodash/lodash.js:3585:27
at /app/thelounge/node_modules/lodash/lodash.js:4967:15
at baseFor0wn (/app/thelounge/node_modules/lodash/lodash.js:3032:24)
at /app/thelounge/node_modules/lodash/lodash.js:4936:18
at baseMap (/app/thelounge/node_modules/lodash/lodash.js:3584:7)
at Function.map(/app/thelounge/node_modules/lodash/lodash.js:9622:14)
Socket. <anonymous> (/app/thelounge/dist/server/server.js:620:26)
Socket.emit (node:events:519:28)
at Socket. emitUntyped (/app/thelounge/node_modules/socket.io/dist/typed-events.js:69:22)